require:
  - rubocop-packaging

AllCops:
  NewCops: enable
  SuggestExtensions: false
  Exclude:
    - '.bundle/**/*'
    - 'spec/fixtures/**/*'
    - 'tmp/**/*'
    - 'vendor/**/*'
  TargetRubyVersion: 2.6

Gemspec/DevelopmentDependencies:
  Enabled: false

Naming/FileName:
  Exclude:
    - lib/rubocop-packaging.rb

Metrics/BlockLength:
  Exclude:
    - tasks/*.rake
  AllowedMethods:
    - configure
    - describe
    - context
    - shared_examples

Metrics/MethodLength:
  Exclude:
    - tasks/*.rake

Style/StringLiterals:
  EnforcedStyle: double_quotes

Style/StringLiteralsInInterpolation:
  EnforcedStyle: double_quotes
